
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IStoreService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IStoreService {


    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "CheckLogin", action = "http://tempuri.org/IStoreService/CheckLogin")
    @WebResult(name = "CheckLoginResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CheckLogin", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckLogin")
    @ResponseWrapper(localName = "CheckLoginResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckLoginResponse")
    public Boolean checkLogin(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

}
